/**
 * Host single-instance guard — vendored copy from
 * `/Users/Ray/TraeProjects/dsh-plugin/dsh-web-ui/packages/dsh-task-board/src/mount-once.ts`.
 *
 * 同步来源：`dsh-web-ui/shared/host/mount-once.ts`（task-board 原版）。如上游
 * 改动，请重新比对再同步本文件 —— vendored copy 的同步由 hello 自己负责。
 *
 * 行为契约：
 *   - 用全局 Symbol 跨同一进程的所有 module 实例共享「已挂载集合」
 *   - 第一次 mount 正常执行，cordis fiber dispose 时清掉标记
 *   - 后续同包名的 mount 是 no-op（防止双注册 webserver routes / system-prompt sections / settings namespaces）
 *   - client 半区天然由 package name dedup，无需 mountOnce
 */

// Generated by sync-shared from shared/host/mount-once.ts. Do not edit this copy;
// edit the shared source and re-sync.
const MOUNTED = Symbol.for('dsh-web-ui.mounted-plugins')

interface MountRegistry {
  [MOUNTED]?: Set<string>
}

function mountedSet(): Set<string> {
  const registry = globalThis as MountRegistry
  return (registry[MOUNTED] ??= new Set())
}

/**
 * Wrap a cordis plugin apply so the package runs at most once per process.
 * @param packageName - npm package identity shared by every install source.
 * @param fn - the original plugin apply.
 * @returns an apply of the same shape.
 */
export function mountOnce<T extends (...args: any[]) => unknown>(packageName: string, fn: T): T {
  return ((...args: unknown[]) => {
    const mounted = mountedSet()
    if (mounted.has(packageName)) return
    mounted.add(packageName)
    const ctx = args[0] as { effect?: (effect: () => unknown) => unknown } | undefined
    ctx?.effect?.(() => () => {
      mounted.delete(packageName)
    })
    return fn(...args)
  }) as T
}